"""empty message

Revision ID: c1ca5a4b3cfd
Revises: 6b5537877f33
Create Date: 2024-10-05 21:58:42.984742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ca5a4b3cfd'
down_revision: Union[str, None] = '6b5537877f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('acquision_datetime', sa.DateTime(), nullable=False))
    op.add_column('location', sa.Column('acquisition_satellite', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'acquisition_satellite')
    op.drop_column('location', 'acquision_datetime')
    # ### end Alembic commands ###
